### ISSUE TITLE
Playback of current song with Spotify

### ISSUE THREAD

**Issue by sbddesign** [PlebFM/PlebFM#27]
Use Spotify API to play a given song by `songId` in the frontend.

## TODO
- [x] Get play/pause to work.
- [x] Automatic transfer of playback from Spotify client
- [x] Create button for dev purposes "Add song to queue"
  - [x] Create api route to add song to queue
  - [x] Connect front end button to api

**Comment by jordan-bravo** [comment]
## TODO
- [x] Get play/pause to work.
- [ ] Automatic transfer of playback from Spotify client
- [ ] Create button for dev purposes "Add song to queue"
