### ISSUE TITLE
V1 Leaderboard

### ISSUE THREAD

**Issue by sbddesign** [PlebFM/PlebFM#30]
This should have:

- [x] Live updates of queue (need https://github.com/PlebFM/PlebFm/issues/15)
- [x] Remove song from Spotify queue (need https://github.com/PlebFM/PlebFM/issues/21)
- [x] Live updates of activity feed (need https://github.com/PlebFM/PlebFm/issues/23)
- [x] Playing current song from Spotify (need https://github.com/PlebFM/PlebFm/issues/27)
- [x] UI effects when songs are added, boosted, and removed (need https://github.com/PlebFM/PlebFm/issues/28)
- [x] Add song to spotify queue (need https://github.com/PlebFM/PlebFM/issues/25)
- [x] Update Spotify queue when 10 seconds from current song end (need #59) 
- [x] And once the above is done, we need to make sure that all of this functions cohesively from the leaderboard and that it's a functional experience for the user.
